# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/abcpig66/abcpig66/blob/main/Untitled1.ipynb
"""

import yfinance as yf
from datetime import datetime, timedelta

# 獲取當前日期
end_date = datetime.today().strftime('%Y-%m-%d')

# 計算開始日期（一個月前）
start_date = (datetime.today() - timedelta(days=30)).strftime('%Y-%m-%d')

# 從 Yahoo Finance 上獲取鴻海（2317.TW）股票的近一個月歷史資料
df = yf.Ticker("2317.TW").history(start=start_date, end=end_date)

# 格式化成交量和成交金額以小數點分隔
df['Volume_Formatted'] = df['Volume'].apply(lambda x: '{:,.0f}'.format(x))
df['Volume_Money'] = df['Volume'] * df['Close']
df['Volume_Money_Formatted'] = df['Volume_Money'].apply(lambda x: '{:,.2f}'.format(x))

# 輸出 DataFrame
df
